### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":"1000000000",
  "amount":12345
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "30eab3889f204d4cae79428363fdb267",
  "accountNumber":"1000000001",
  "amount":12345
}

### query transaction
GET http://localhost:8080/transaction/30eab3889f204d4cae79428363fdb267

}