### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":"1000000000",
  "amount":12345
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId" : "782170096a894e08a5ce56909da8e4c4",
  "accountNumber":"1000000001",
  "amount":12345
}